title: Walkthrough
author: michael
email: moathgaleb@yahoo.com
description: Welcome to hell

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Moathgaleb

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
